minecraft-server:
  image: "itzg/minecraft-server:armv7"
  container_name: "mc-pi"

  ports:
    - "25565:25565"
    - "4711:4711"

  volumes:
    - "/opt/minecraft/data:/data"
    - "/opt/minecraft/plugins:/plugins"

  environment:
    TZ: 'America/Chicago'
    OPS: "Mari0__"
    HARDCORE: "false"
    SPAWN_ANIMALS: "true"
    SPAWN_MONSTERS: "true"
    SPAWN_NPCS: "true"
    SPAWN_PROTECTION: 0
    MODE: "creative"
    ONLINE_MODE: "false"
    ALLOW_FLIGHT: "true"
    MEMORY: "800M"
    GUI: "false"
    MAX_TICK_TIME: 100000
    EULA: "TRUE"
    TYPE: "SPIGOT"
    VERSION: "1.15.2"

  tty: true
  stdin_open: true
  restart: unless-stopped