---
- hosts: pi_torrents
  vars:
    ansible_python_interpreter: /usr/bin/python3
    sonarr_name: sonarr
    sonarr_image: linuxserver/sonarr
    sonarr_ports:
      - 8989:8989
      - 9898:9898
    sonarr_config_directory: /opt/sonarr
    sonarr_tv_directory: /media/videos
    sonarr_download_directory: /media/videos/tmp
    sonarr_environment_variables:
      PUID: "1000"
      PGID: "1000"
      TZ: America/Chicago
    sonarr_docker_additional_options:
      restart_policy: unless-stopped
    sonarr_config:
      UrlBase: "192.168.1.32"
      LaunchBrowser: "False"
      AnalyticsEnabled: "False"

  pre_tasks:
    - name: 'Make sonarr config dir'
      become: yes
      file:
        path: /opt/sonarr
        group: docker
        state: directory
    - name: 'Make radarr config dir'
      become: yes
      file:
        path: /opt/radarr
        group: docker
        state: directory
    - name: 'Make transmission config dir'
      become: yes
      file:
        path: /opt/transmission
        group: docker
        state: directory
    - name: 'Make jackett config dir'
      become: yes
      file:
        path: /opt/jackett
        group: docker
        state: directory
  tasks:
    - name: radarr container
      docker_container:
        name: radarr
        image: linuxserver/radarr
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "7878:7878"
        env:
          TZ: "America/Chicago"
          PGID: "1000"
          PUID: "1000"
        volumes:
          - /opt/radarr:/config
          - /media/videos:/movies
          - /media/videos/tmp:/downloads
    - name: sonarr container
      docker_container:
        name: sonarr
        image: linuxserver/sonarr
        state: started
        restart_policy: unless-stopped
        published_ports:
          - 8989:8989
          - 9898:9898
        env:
          TZ: "America/Chicago"
          PGID: "1000"
          PUID: "1000"
        volumes:
          - /opt/sonarr:/config
          - /media/videos:/tv
          - /media/videos/tmp:/downloads
    - name: transmission container
      docker_container:
        name: transmission
        image: linuxserver/transmission
        state: started
        restart_policy: unless-stopped
        published_ports:
          - 9091:9091
          - 51413:51413
          - 51413:51413/udp
        env:
          TZ: "America/Chicago"
          PGID: "1000"
          PUID: "1000"
        volumes:
          - /opt/transmission:/config
          - /media/videos/tmp:/downloads
    - name: Jackett container
      docker_container:
        name: jackett
        image: linuxserver/jackett
        state: started
        restart_policy: unless-stopped
        published_ports:
          - 9117:9117
        env:
          TZ: "America/Chicago"
          PGID: "1000"
          PUID: "1000"
        volumes:
          - /opt/jackett:/config
          - /media/videos/tmp:/downloads
